// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGTP4AH02qGgVClzFX2KpGYSY5jVND584',
    appId: '1:442511002985:android:59d62f08f761e5c7d241f8',
    messagingSenderId: '442511002985',
    projectId: 'firestoredemo-16c50',
    databaseURL: 'https://firestoredemo-16c50.firebaseio.com',
    storageBucket: 'firestoredemo-16c50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCotiEm6SO3efWEY0iuW1CIcBh8VKC_J5c',
    appId: '1:442511002985:ios:e8ddbd0ad6c8ca36d241f8',
    messagingSenderId: '442511002985',
    projectId: 'firestoredemo-16c50',
    databaseURL: 'https://firestoredemo-16c50.firebaseio.com',
    storageBucket: 'firestoredemo-16c50.appspot.com',
    iosClientId: '442511002985-rq3406cancg883ii8mhm44agrqe0q4sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.robbinlaw',
  );
}
